# Generated by Django 6.0.3 on 2026-04-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_room_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='building',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='campus',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
