# Generated by Django 6.0.3 on 2026-05-08 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_member'),
        ('testApp', '0003_remove_reservation_building_remove_reservation_email_and_more'),
    ]

    operations = [
    ]
