# Generated by Django 6.0.4 on 2026-04-23 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0004_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testApp.building'),
        ),
    ]
