# Generated by Django 5.2.11 on 2026-05-11 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0004_merge_20260508_0007'),
        ('testApp', '0005_alter_checkin_building'),
    ]

    operations = [
    ]
