# Generated by Django 6.0.2 on 2026-04-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('campus', models.CharField(max_length=100)),
                ('floor_count', models.IntegerField(default=1)),
            ],
        ),
    ]
