# Generated by Django 6.0.2 on 2026-04-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phone', models.IntegerField(null=True)),
                ('joined_date', models.DateField(null=True)),
                ('Email', models.CharField(null=True)),
            ],
        ),
    ]
